---
- block:
  - name: Ensure NTP package is installed
    ansible.builtin.package:
      name: ntp
      state: present

  - name: Ensure NTP service is started and enabled
    service:
      name: ntp
      state: started
      enabled: true

- name: Set Hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: Configuring SELinux
  block:
    - name: Installing required packages
      ansible.builtin.package:
        name:
          - libselinux-python3
          - iproute-tc
        state: present

    - name: Putting SELinux in permissive mode
      ansible.posix.selinux:
        policy: targeted
        state: permissive
      notify: Reboot Machine
  when: ansible_distribution == 'CentOS'

- name: Rebooting Now
  ansible.builtin.meta: flush_handlers

- name: Enabling kernal modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Creating /etc/sysctl.d/99-kubernetes-cri.conf
  ansible.builtin.copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload sysctl

- name: Applying sysctl.d/99-kubernetes-cri.conf
  ansible.builtin.command: sysctl --system
  changed_when: false

- name: Checking Linux swap status
  ansible.builtin.command: swapon --show
  register: swap_check
  changed_when: false

- name: Disabling Linux swap file
  ansible.builtin.command: swapoff -a
  when: swap_check.stdout | length > 0

- name: Ensuring swap stays disabled
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: ^/(.*)swap(.*)
    line: '#/\1swap\2'
    backrefs: true
    backup: true

- name: Install and Configure Docker
  ansible.builtin.include_tasks: cri-dockerd.yml

- name: Run OS specific tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "common-{{ ansible_distribution }}.yml"

- name: Starting and Enabling kubelet
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true
