---
- name: Configure HAProxy on Controlplane
  include_tasks: haproxy.yml
  when: "'controlplane_master' in group_names or 'controlplane_slave' in group_names"

- name: Common Configuration
  include_tasks: common.yml

- name: Configure Controlplane
  include_tasks: master.yml
  when: "'controlplane_master' in group_names or 'controlplane_slave' in group_names"

- name: Configure CNI on Controlplane Master
  include_tasks: cni.yml
  when: "'controlplane_master' in group_names"

- name: Configure Nodes
  include_tasks: node.yml
  when: "'worker' in group_names"
