---
- name: Restart RKE2 Server
  ansible.builtin.systemd:
    name: rke2-server
    state: restarted
  timeout: 600

- name: Restart RKE2 Agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: restarted
  timeout: 600
