---
- name: Reboot Machine
  ansible.builtin.reboot:
    reboot_timeout: 300

- name: Reload sysctl
  ansible.builtin.command: sysctl -p --system

- name: Restart HAProxy
  service:
    name: haproxy
    state: restarted

- name: Restart Keepalived
  service:
    name: keepalived
    state: restarted
