---
- name: Add NFS provisioner Helm repository
  kubernetes.core.helm_repository:
    name: nfs-provisioner
    repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

- name: Install NFS provisioner
  kubernetes.core.helm:
    name: "{{ nfs_provisioner_name }}"
    chart_ref: nfs-provisioner/nfs-subdir-external-provisioner
    release_namespace: "{{ nfs_namespace }}"
    release_name: nfs-provisioner
    create_namespace: true
    release_state: present
    context: "{{ context_name }}"
    values:
      nfs:
        server: "{{ nfs_server }}"
        path: "{{ nfs_path }}"
      storageClass:
        name: "{{ nfs_storage_class_name }}"
        provisionerName: k8s-sigs.io/second-nfs-subdir-external-provisioner
        reclaimPolicy: "{{ nfs_reclaim_policy }}"
        defaultClass: "{{ nfs_default_class }}"
