---
- name: Create RKE2 config file
  ansible.builtin.template:
    src: templates/config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0644"
  register: rke2_config_result

- name: Run RKE2 Agent Install Script
  ansible.builtin.shell: curl -sfL https://get.rke2.io | sh - 2>&1 | tee /var/log/rke2-install.log
  environment:
    INSTALL_RKE2_TYPE: agent
    INSTALL_RKE2_VERSION: "{{ rke2_version | default(omit) }}"
  args:
    creates: /var/lib/rancher/rke2

- name: Gather Service Facts
  ansible.builtin.service_facts:

- name: Start RKE2 Agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: started
    enabled: true
  register: rke2_agent_start
  until: rke2_agent_start.status.ActiveState == 'active'
  retries: 2
  delay: 5

- name: Restart RKE2 Agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: restarted
  when:
    - rke2_config_result is changed
    - ansible_facts.services['rke2-agent.service'].state == 'running'
