---
- name: Create RKE2 config file
  ansible.builtin.template:
    src: templates/config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0644"
  register: rke2_config_result

- name: Run RKE2 Agent Install Script
  ansible.builtin.shell: curl -sfL https://get.rke2.io | sh -
  environment:
    INSTALL_RKE2_TYPE: agent
    INSTALL_RKE2_VERSION: "{{ rke2_version | default(omit) }}"
  args:
    creates: /var/lib/rancher/rke2

- name: Check if RKE2 Agent is running
  ansible.builtin.systemd:
    name: rke2-agent
    state: started
  register: rke2_agent_status

- name: Start RKE2 Agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: started
    enabled: true
  when: rke2_agent_status.status.ActiveState != "active"
  timeout: 900

- name: Restart RKE2 Agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: restarted
  when:
    - rke2_config_result is changed
    - rke2_agent_status.status.ActiveState == "active"
