---
- name: Create RKE2 directory
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: "0755"

- name: Touch RKE2 Config File
  ansible.builtin.file:
    path: /etc/rancher/rke2/config.yaml
    state: touch
    mode: "0644"

- name: Disable IPv6 in RKE2
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "disable-ipv6: true"
  when: rke2_disable_ipv6 | bool
  notify: Restart RKE2

- name: Disable Nginx Ingress
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: |
      disable:
        - rke2-ingress-nginx
  when: rke2_disable_ingress_nginx | bool
  notify: Restart RKE2

- name: Set RKE2 Server URL
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "server: https://{{ hostvars[groups['controlplane_master'][0]]['ansible_default_ipv4']['address'] }}:9345"
  when: "'controlplane_master' not in group_names"
  notify: Restart RKE2

- name: Set Container Registry Mirrors
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: |
      mirrors:

- name: Set docker.io Registry Mirror
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    insertafter: "mirrors:"
    line: |
        docker.io:
          endpoint:
            - "{{ rke2_dockerio_mirror }}"
  when: rke2_dockerio_mirror is defined
  notify: Restart RKE2

- name: Set index.docker.io Registry Mirror
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    insertafter: "mirrors:"
    line: |
      index.docker.io:
        endpoint:
          - "{{ rke2_indexdockerio_mirror }}"
  when: rke2_indexdockerio_mirror is defined
  notify: Restart RKE2

- name: Set max-pods
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: |
      kubelet-arg:
        - "max-pods={{ rke2_max_pods }}"
  when: rke2_max_pods is defined
  notify: Restart RKE2

- name: Install nftables
  ansible.builtin.package:
    name: nftables
    state: present

- name: Check if firewalld is installed
  ansible.builtin.command: systemctl status firewalld
  register: firewalld_status
  ignore_errors: true
  changed_when: false

- name: Open Firewall Ports
  when: firewalld_status.rc == 0
  block:
    - name: Install python3-firewall
      ansible.builtin.package:
        name: python3-firewall
        state: present

    - name: Open Firewall Ports for all nodes
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - 10250/tcp
        - 8472/udp
        - 30000-32767/tcp

    - name: Open Firewall Ports for controlplane nodes
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - 6443/tcp
        - 9345/tcp
        - 2379-2380/tcp
        - 2381/tcp
      when: "'controlplane' in group_names"

- name: Configure Main RKE2 Server
  ansible.builtin.include_tasks: server.yml
  when: "'controlplane_master' in group_names"

- name: Configure Additional RKE2 Servers
  ansible.builtin.include_tasks: server.yml
  when: "'controlplane_slave' in group_names"

- name: Configure Agents
  ansible.builtin.include_tasks: agent.yml
  when: "'worker' in group_names"
