---
- name: Create RKE2 directory
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'

- name: Touch RKE2 Config File
  ansible.builtin.file:
    path: /etc/rancher/rke2/config.yaml
    state: touch
    mode: '0644'

- name: Disble Nginx Ingress
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: |
      disable:
        - rke2-ingress-nginx
  when: rke2_disable_ingress_nginx | bool

- name: Set RKE2 Server URL
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "server: https://{{ hostvars[groups['controlplane_master'][0]]['ansible_default_ipv4']['address'] }}:9345"
  when: "'controlplane_master' not in group_names"

- name: Set Container Registry Mirrors
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: |
      mirrors:
        docker.io:
          endpoint:
            - "{{ rke2_registry_mirrors }}"
        ghcr.io:
          endpoint:
            - "{{ rke2_registry_mirrors }}"
  when: rke2_registry_mirrors | length > 0

- name: Configure Main RKE2 Server
  include_tasks: server.yml
  when: "'controlplane_master' in group_names"

- name: Configure Additional RKE2 Servers
  include_tasks: server.yml
  when: "'controlplane_slave' in group_names"

- name: Configure Agents
  include_tasks: agent.yml
  when: "'worker' in group_names"
