---
- name: Check if firewalld is installed
  ansible.builtin.stat:
    path: /usr/bin/firewall-cmd
  register: firewalld_installed

- name: Open Firewall Ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - 9345/tcp
    - 6443/tcp
  when: firewalld_installed.stat.exists
  ignore_errors: true

- name: Create RKE2 config file
  ansible.builtin.template:
    src: templates/config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0644"
  register: rke2_config_result

- name: Run RKE2 Server Install Script # noqa: command-instead-of-module
  ansible.builtin.shell: curl -sfL https://get.rke2.io | sh -
  environment:
    INSTALL_RKE2_VERSION: "{{ rke2_version | default(omit) }}"
    INSTALL_RKE2_TYPE: server
  args:
    creates: /var/lib/rancher/rke2

- name: Check if RKE2 Server is running
  ansible.builtin.command: "systemctl is-active rke2-server"
  register: rke2_server_status
  failed_when: false
  changed_when: false

- name: Start RKE2 Server if not running
  ansible.builtin.systemd:
    name: rke2-server
    state: started
    enabled: true
  when: rke2_server_status.rc != 0
  register: rke2_server_start
  until: rke2_server_start is succeeded
  retries: 2
  delay: 5

- name: Restart RKE2 Server if config changed
  ansible.builtin.systemd:
    name: rke2-server
    state: restarted
  when:
    - rke2_config_result is changed
    - rke2_server_status.rc == 0

- name: Register RKE2 Token
  ansible.builtin.command: cat /var/lib/rancher/rke2/server/node-token
  register: rke2_token
  failed_when: false
  changed_when: false
  when: "'controlplane_master' in group_names"
