---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Open Firewall Ports
  when: >
    'firewalld.service' in ansible_facts.services and
    ansible_facts.services['firewalld.service'].state is defined and
    ansible_facts.services['firewalld.service'].state == 'running'
  block:
    - name: Install python3-firewall
      ansible.builtin.package:
        name: python3-firewall
        state: present

    - name: Open Firewall Ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - 9345/tcp
        - 6443/tcp

- name: Create RKE2 config file
  ansible.builtin.template:
    src: templates/config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0644"
  register: rke2_config_result

- name: Run RKE2 Server Install Script # noqa: command-instead-of-module
  ansible.builtin.shell: curl -sfL https://get.rke2.io | sh -
  environment:
    INSTALL_RKE2_VERSION: "{{ rke2_version | default(omit) }}"
    INSTALL_RKE2_TYPE: server
  args:
    creates: /var/lib/rancher/rke2

- name: Check if RKE2 Server is running
  ansible.builtin.systemd:
    name: rke2-server
    state: started
  register: rke2_server_status

- name: Start RKE2 Server
  ansible.builtin.systemd:
    name: rke2-server
    state: started
    enabled: true
  when: rke2_server_status.status.ActiveState != "active"
  register: rke2_server_start
  until: rke2_server_start is succeeded
  retries: 2
  delay: 5

- name: Restart RKE2 Server
  ansible.builtin.systemd:
    name: rke2-server
    state: restarted
  when:
    - rke2_config_result is changed
    - rke2_server_status.status.ActiveState == "active"

- name: Register RKE2 Token
  ansible.builtin.command: cat /var/lib/rancher/rke2/server/node-token
  register: rke2_token
  failed_when: false
  changed_when: false
  when: "'controlplane_master' in group_names"
