---
- name: Check if firewalld is running
  ansible.builtin.systemd:
    name: firewalld
    state: started
  register: firewalld_running
  changed_when: false

- name: Open Firewall Ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - 9345/tcp
    - 6443/tcp
  when: firewalld_running.status == 'started'

- name: Add RKE2 Server Token
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: 'token: "{{ hostvars[groups[''controlplane_master''][0]][''rke2_token''][''stdout''] }}"'
  when: "'controlplane_slave' in group_names"

- name: Taint Controlplane
  ansible.builtin.lineinfile:
    path: /etc/rancher/rke2/config.yaml
    line: |
      node-taint:
        - "CriticalAddonsOnly=true:NoExecute"
  when: "rke2_taint_control_plane"

- name: Run RKE2 Server Install Script
  ansible.builtin.shell: curl -sfL https://get.rke2.io | sh -
  environment:
    INSTALL_RKE2_VERSION: "{{ rke2_version | default(omit) }}"
  args:
    creates: /var/lib/rancher/rke2

- name: Start RKE2 Server
  ansible.builtin.systemd:
    name: rke2-server
    state: started
    enabled: true

- name: Register RKE2 Token
  when: "'controlplane_master' in group_names"
  block:
    - name: Register RKE2 Token
      ansible.builtin.command: cat /var/lib/rancher/rke2/server/node-token
      register: rke2_token
      failed_when: false
      changed_when: false

    - name: Retrieve kubectl config from remote host
      ansible.builtin.fetch:
        src: /etc/rancher/rke2/rke2.yaml
        dest: "~/.kube/{{ context_name | default('config') }}"
        flat: true
        mode: "0600"
      when: rke2_copy_kubeconfig
