---
- name: Create K3s directory
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: "0755"

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Install nftables
  ansible.builtin.package:
    name: nftables
    state: present

- name: Disable IPv6 on all interfaces
  ansible.builtin.sysctl:
    name: "{{ item }}"
    value: 1
    state: present
    sysctl_set: true
    reload: true
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  when: k3s_disable_ipv6 | bool

- name: Ensure IPv6 kernel module is disabled
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/disable-ipv6.conf
    line: "install ipv6 /bin/true"
    create: true
    mode: "0644"
  when: k3s_disable_ipv6 | bool

- name: Open Firewall Ports
  when: >
    'firewalld.service' in ansible_facts.services and
    ansible_facts.services['firewalld.service'].state is defined and
    ansible_facts.services['firewalld.service'].state == 'running'
  block:
    - name: Install python3-firewall
      ansible.builtin.package:
        name: python3-firewall
        state: present

    - name: Open Firewall Ports for all nodes
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - 10250/tcp
        - 8472/udp
        - 30000-32767/tcp
      ignore_errors: true

    - name: Open Firewall Ports for controlplane nodes
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - 6443/tcp
        - 9345/tcp
        - 2379-2380/tcp
        - 2381/tcp
      when: "'controlplane' in group_names"
      ignore_errors: true

- name: Configure Main K3s Server
  ansible.builtin.include_tasks: server.yml
