---
- name: Create K3s config file
  ansible.builtin.template:
    src: templates/config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: "0644"
  register: k3s_config_result

- name: Gather Service Facts
  ansible.builtin.service_facts:

- name: Set initial install flag
  ansible.builtin.set_fact:
    k3s_initial_install: "{{ 'k3s.service' not in ansible_facts.services }}"

- name: Run K3s Server Install Script # noqa: command-instead-of-module
  ansible.builtin.shell: curl -sfL https://get.k3s.io | sh - 2>&1 | tee /var/log/k3s-install.log
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version | default(omit) }}"
  args:
    creates: /var/lib/rancher/k3s

- name: Restart K3s Server
  ansible.builtin.systemd:
    name: k3s
    state: restarted
  when:
    - k3s_config_result is changed
    - ansible_facts.services['k3s.service'] is defined
    - ansible_facts.services['k3s.service'].state == 'running'
    - not k3s_initial_install | bool
