---
- name: Adding Kubernetes Repository
  ansible.builtin.copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644

- name: Installing K8s Packages
  ansible.builtin.yum:
    name:
      - kubelet-1.25.5-0
      - kubelet-1.25.5-0
      - kubelet-1.25.5-0
    state: installed
    disable_excludes: all
    exclude: kubernetes
