---
- name: Install HAProxy and Keepalived
  ansible.builtin.include_tasks: haproxy.yml
  vars:
    state: "MASTER"
  when: inventory_hostname in groups['controlplane_master']

- name: Install HAProxy and Keepalived
  ansible.builtin.include_tasks: haproxy.yml
  vars:
    state: "SLAVE"
  when: inventory_hostname in groups['controlplane_slave']
